name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
  test:
    strategy:
      matrix:
        go-version: [ 1.17.x, 1.18.x, 1.x ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - uses: actions/checkout@v3

      - name: Check
        run: make check

      - name: build
        run: make clean build

      - name: test
        run: make test

        # only report code coverage on linux
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./cover.out
          name: goprod-${{ matrix.go-version }}

      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: "**/TEST-*.xml"
        if: always()