name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
      - uses: actions/checkout@v3

      - name: Check
        run: make check

      - name: build
        run: make clean build

      - name: test
        run: make test

        # only report code coverage on linux
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./cover.out
          name: goprod

      - name: Create test summary
        uses: test-summary/action@v1
        with:
          paths: unit-tests.xml
          output: test-results.html
        if: always()
      - name: Upload test summary
        uses: actions/upload-artifact@v3
        with:
          name: test-summary
          path: test-results.html
        if: always()